### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by baldurmen** [RecursiveForest/whatmp3#37]
Hi!

I like whatmp3 and I use it often, but it seems this repository is somewhat stale...

Do you intend to keep working on this? If not, giving commit rights to @robinwils would be nice! They seem to have kept working on this project and maybe would be interested in maintaining it in the future?

If new releases of whatmp3 are made, i'd be open to the idea of creating and maintaining a Debian package for it.

Cheers!

**Comment by robinwils** [comment]
Hey !

I have made some changes on my fork of this repo if you are interested.

I could try maintaining this repo, I added some features in my forked version that could be useful in this one.

Making a debian package for it (or any other distribution) can also be interesting
There are pending Pull requests, I assume @RecursiveForest isn't actively looking at this repo

**Comment by baldurmen** [comment]
@RecursiveForest ping! I'd really like to be able to get this into the next Debian stable release (Debian 11) and that takes a bit of time...

**Comment by RecursiveForest** [comment]
@baldurmen I've since pushed a few fixes addressing issues brought up since I was last active. I have plans to add some testing with `pytest` and improve packaging by using `poetry` to make the project more mature. I haven't received much in the way of PRs for a long time though as most people are contributing to forked projects now under various names.
